# Base URL, all other subpages wil share this prefix
baseURL: ""

# Language
languageCode: en-us

# Title
title: "Blog"

# The default theme for the blog
theme: ["PaperMod"]

# Params of theme
params:
  defaultTheme: auto

  profileMode:
    enabled: true
    title: "Welcome to my home" # optional default will be site title
    subtitle: "My personal blog for Cryptography and CTFs"
    imageURL: "logo.jpg"
    imageTitle: "Yes. It's a capybara"
    imageWidth: 400
    imageHeight: 400

  cover:
    linkFullImages: true

  homeInfoParams:
    Title: Hi there
    Content: Home sweet home

  socialIcons: # optional
    - name: facebook
      url: https://www.facebook.com/
    - name: twitter
      url: https://www.twitter.com/
    - name: linkedin
      url: https://www.linkedin.com/
    - name: github
      url: https://www.github.com/
    - name: email
      url: "mailto:info@example.com"

  ShowBreadcrumbs: true
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true

menu:
  main:
    - identifier: about
      name: About
      url: "/about"
      weight: 1
    - identifier: posts
      name: Posts
      url: "/posts"
      weight: 2
    - identifier: archives
      name: Archives
      url: "/archives"
      weight: 3
    - identifier: tags
      name: Tags
      url: "/tags"
      weight: 4
