# Base URL, all other subpages wil share this prefix
baseURL: "https://happyfalcon22.github.io/"

# Language
languageCode: en-us

# Title
title: "Blog"

# The default theme for the blog
theme: ["PaperMod"]

# Params of theme
params:
  defaultTheme: auto

  cover:
    linkFullImages: true

  homeInfoParams:
    Title: Hi there
    Content: Home sweet home

  socialIcons: # optional
    - name: facebook
      url: https://www.facebook.com/
    - name: "email"
      url: "https://www.facebook.com/"

  ShowBreadcrumbs: true
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true

menu:
  main:
    - identifier: about
      name: About
      url: "/about"
      weight: 1
    - identifier: posts
      name: Posts
      url: "/posts"
      weight: 2
    - identifier: archives
      name: Archives
      url: "/archives"
      weight: 3
    - identifier: tags
      name: Tags
      url: "/tags"
      weight: 4
